from __future__ import annotations

from casino_lab4.simulation.casino import Casino

def event_roulette(casino: Casino) -> None: ...
def event_slots(casino: Casino) -> None: ...
def event_honk_scream(casino: Casino) -> None: ...
def event_wargoose_attack(casino: Casino) -> None: ...
def event_sanity_break(casino: Casino) -> None: ...
